<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Embedded\verseIndex.dat" />
    <None Remove="Embedded\verses.dat" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Embedded\verseIndex.dat" />
    <EmbeddedResource Include="Embedded\verses.dat" />
  </ItemGroup>

</Project>
