<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android</TargetFramework>
	<SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
    <OutputType>Exe</OutputType>
    <AndroidApplication>True</AndroidApplication>
    <AndroidResgenFile>Resources\Resource.Designer.cs</AndroidResgenFile>
    <AndroidResgenClass>Resource</AndroidResgenClass>
    <AndroidManifest>Properties\AndroidManifest.xml</AndroidManifest>
    <MonoAndroidResourcePrefix>Resources</MonoAndroidResourcePrefix>
    <MonoAndroidAssetsPrefix>Assets</MonoAndroidAssetsPrefix>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
    <ApplicationVersion>20000</ApplicationVersion>
    <ApplicationDisplayVersion>2.0.0</ApplicationDisplayVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <AndroidUseSharedRuntime>True</AndroidUseSharedRuntime>
    <AndroidLinkMode>None</AndroidLinkMode>
    <EmbedAssembliesIntoApk>False</EmbedAssembliesIntoApk>
    <MandroidI18n />
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <AndroidManagedSymbols>true</AndroidManagedSymbols>
    <AndroidUseSharedRuntime>False</AndroidUseSharedRuntime>
    <AndroidLinkMode>Full</AndroidLinkMode>
	<AndroidLinkTool>r8</AndroidLinkTool>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
    <EnableProguard>true</EnableProguard>
	<RunAOTCompilation>true</RunAOTCompilation>
	<AndroidEnableProfiledAot>True</AndroidEnableProfiledAot>
    <EnableLLVM>true</EnableLLVM>
    <TrimMode>full</TrimMode>
	<AndroidSigningKeyStore>D:\android.keystore</AndroidSigningKeyStore>
	<AndroidSigningKeyAlias>nito</AndroidSigningKeyAlias>
	<AndroidSigningStorePass>env:AndroidSigningPassword</AndroidSigningStorePass>
	<AndroidSigningKeyPass>env:AndroidSigningPassword</AndroidSigningKeyPass>
	<RuntimeIdentifiers>android-arm;android-arm64;android-x86;android-x64</RuntimeIdentifiers>
	<AndroidCreatePackagePerAbi>True</AndroidCreatePackagePerAbi>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PewBibleKjv.Logic\PewBibleKjv.Logic.csproj" />
    <ProjectReference Include="..\PewBibleKjv.Text\PewBibleKjv.Text.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AndroidEnvironment Include="Environment.txt" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Xamarin.AndroidX.AppCompat" Version="1.7.1.1" />
    <PackageReference Include="Xamarin.AndroidX.ConstraintLayout" Version="2.2.1.3" />
    <PackageReference Include="Xamarin.AndroidX.RecyclerView" Version="1.4.0.3" />
  </ItemGroup>
</Project>